### PR TITLE
Baladraft

### PR DESCRIPTION
**Pull request by Bala667**
Hello eva,

I made the changes for Ethernet IP connector please review and let me know your comments

Thanks
Balaguru

### CODE REVIEW

**Comment by EvaKaul** [comment]
Hi Bala,
I did the review and I have some comments/findings:

**Readme.md**

- complete the list of supported PLC types; according to the manual there are some more...

- _IEM: Installed system Databus configurator **for Databus**_ -> delete the bold

- complete the list of required apps OR combine the marked lines, e.g.:
**_IED: Installed apps according to components list below_**
image

- Check: is the Common Import Converter necessary too?

**Installation.md**

- Chapter 'Configure Ethernet IP via Common Configurator'
-> before deploying you need to activate the 'pubish on databus' option for each tag
-> E.g. _'For writing the tag values onto the MQTT databus you need to activate and confirm the 'Publish on the databus' option for each tag.'_
image
image

File **Flow.json**

- adapt the var IDs within the inject nodes for writing (hardcoded > should be ID ‘3’ to write on ‘Var_REAL’)
image

**In general** (just a formal point):
- add frames to the screenshots (like explained [here](https://github.com/industrial-edge/how-to-template/blob/main/docs/Installation.md#add-additional-installation-steps-here-if-required))

**Review by EvaKaul — APPROVED** [review]
see comments/feedback in conversation chat

**Comment by Bala667** [comment]
> Hi Bala, I did the review and I have some comments/findings:
> 
> **Readme.md**
> 
> * complete the list of supported PLC types; according to the manual there are some more...
> * _IEM: Installed system Databus configurator **for Databus**_ -> delete the bold
> * complete the list of required apps OR combine the marked lines, e.g.:
>   **_IED: Installed apps according to components list below_**
>   image
> * Check: is the Common Import Converter necessary too?
> 
> **Installation.md**
> 
> * Chapter 'Configure Ethernet IP via Common Configurator'
>   -> before deploying you need to activate the 'pubish on databus' option for each tag
>   -> E.g. _'For writing the tag values onto the MQTT databus you need to activate and confirm the 'Publish on the databus' option for each tag.'_
>   image
>   image
> 
> File **Flow.json**
> 
> * adapt the var IDs within the inject nodes for writing (hardcoded > should be ID ‘3’ to write on ‘Var_REAL’)
>   image
> 
> **In general** (just a formal point):
> 
> * add frames to the screenshots (like explained [here](https://github.com/industrial-edge/how-to-template/blob/main/docs/Installation.md#add-additional-installation-steps-here-if-required))

**Comment by EvaKaul** [comment]
Changes after review ok.
Pull request can be merged.

**Pull request merged**
